# Generated by Django 4.2.7 on 2023-12-09 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "balance_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Credor"), (2, "Devedor")],
                        verbose_name="Tipo de Saldo",
                    ),
                ),
                (
                    "account_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Ativo"),
                            (2, "Passivo"),
                            (3, "Patrimônio Líquido"),
                            (4, "Subdivisão"),
                        ],
                        verbose_name="Tipo de Conta",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.account",
                        verbose_name="Conta Pai",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Balanço",
                "verbose_name_plural": "Itens do Balanço",
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Crédito"), (2, "Débito")],
                        verbose_name="Tipo de Operação",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_operation",
                        to="core.account",
                        verbose_name="Conta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operação",
                "verbose_name_plural": "Operações",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "next",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="previous",
                        to="core.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transação",
                "verbose_name_plural": "Transações",
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity", models.CharField(default="", max_length=255)),
                (
                    "base_currency",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "BRL"),
                            (2, "USD"),
                            (3, "EUR"),
                            (4, "JPY"),
                            (5, "GBP"),
                            (6, "CNY"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "current_currency",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "BRL"),
                            (2, "USD"),
                            (3, "EUR"),
                            (4, "JPY"),
                            (5, "GBP"),
                            (6, "CNY"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="N BC/1 CC",
                        max_digits=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("document", models.FileField(blank=True, upload_to="")),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_meta",
                        to="core.operation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="operation",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_operation",
                to="core.transaction",
                verbose_name="Transação",
            ),
        ),
    ]
