# Generated by Django 4.2.7 on 2023-12-13 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"verbose_name": "Conta", "verbose_name_plural": "Contas"},
        ),
        migrations.AlterModelOptions(
            name="operationmeta",
            options={
                "verbose_name": "Detalhe da Operação",
                "verbose_name_plural": "Detalhes das Operações",
            },
        ),
        migrations.AlterModelOptions(
            name="setting",
            options={
                "verbose_name": "Configuração",
                "verbose_name_plural": "Configurações",
            },
        ),
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Ativo"),
                    (2, "Passivo"),
                    (3, "Patrimônio Líquido"),
                    (4, "Subdivisão"),
                    (5, "Receitas"),
                    (6, "Despesas"),
                ],
                verbose_name="Tipo de Conta",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="base_currency",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "BRL"),
                    (2, "USD"),
                    (3, "EUR"),
                    (4, "JPY"),
                    (5, "GBP"),
                    (6, "CNY"),
                ],
                default=1,
                verbose_name="Moeda base",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="current_currency",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "BRL"),
                    (2, "USD"),
                    (3, "EUR"),
                    (4, "JPY"),
                    (5, "GBP"),
                    (6, "CNY"),
                ],
                default=1,
                verbose_name="Moeda atual",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="entity",
            field=models.CharField(default="", max_length=255, verbose_name="Entidade"),
        ),
        migrations.AlterField(
            model_name="setting",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="N BC/1 CC",
                max_digits=10,
                verbose_name="Taxa de câmbio",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_settings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
