# Generated by Django 4.2.7 on 2023-12-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_accountingperiod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountingperiod",
            name="end_date",
            field=models.DateField(null=True),
        ),
    ]
