# Generated by Django 4.2.7 on 2023-12-15 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_alter_accountingperiod_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingperiod",
            name="user",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_accounting_period",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Período Contábil",
            ),
            preserve_default=False,
        ),
    ]
