# Generated by Django 4.2.7 on 2023-12-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_accountingperiod_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingperiod",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Em Curso"),
                    (2, "Fechamento de Contas"),
                    (3, "Finalizado"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
    ]
