# Generated by Django 4.2.7 on 2023-12-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_transaction_created_at_transaction_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="defined_first_period",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Ativo"),
                    (2, "Passivo"),
                    (3, "Patrimônio Líquido"),
                    (4, "Subdivisão"),
                    (5, "Receitas"),
                    (6, "Despesas"),
                    (7, "Resultado"),
                ],
                verbose_name="Tipo de Conta",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="balance_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Credor"), (2, "Devedor"), (3, "Indefinido")],
                verbose_name="Tipo de Saldo",
            ),
        ),
    ]
