# Generated by Django 4.2.7 on 2023-12-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_setting_defined_first_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
