# Generated by Django 4.2.7 on 2023-12-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_transaction_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="root_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Ativo"),
                    (2, "Passivo"),
                    (3, "Patrimônio Líquido"),
                    (4, "Subdivisão"),
                    (5, "Receitas"),
                    (6, "Despesas"),
                    (7, "Resultado"),
                ],
                null=True,
            ),
        ),
    ]
