# Generated by Django 4.2.7 on 2023-12-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_account_root_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="theme",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Claro"), (2, "Escuro"), (3, "Automático")],
                default=1,
                verbose_name="Tema",
            ),
        ),
    ]
