# Generated by Django 4.2.8 on 2024-08-21 19:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_setting_theme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="setting",
            name="theme",
        ),
    ]
